# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-26 10:57
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coordinate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('latitude', models.DecimalField(decimal_places=8, default=0, max_digits=10, validators=[django.core.validators.MaxValueValidator(90, message='Latitude must be up to 90'), django.core.validators.MinLengthValidator(-90, message='Latitude must be a minimum of                 -90')])),
            ],
            options={
                'db_table': 'coordinates',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=64, validators=[django.core.validators.MaxLengthValidator(100, message='Name must be at most 100                                    characters'), django.core.validators.MinLengthValidator(3, message='Name must be at least 3                                    characters')])),
                ('email', models.EmailField(max_length=100, unique=True, validators=[django.core.validators.MaxLengthValidator(100, message='Email must be at most 100                                    characters'), django.core.validators.MinLengthValidator(3, message='Email must be at least 3                                    characters'), django.core.validators.EmailValidator(message='Invalid email adress')])),
                ('address', models.CharField(max_length=100, validators=[django.core.validators.MaxLengthValidator(100, message='Address must be at most 100                                    characters'), django.core.validators.MinLengthValidator(3, message='Address must be at least 3                                    characters')])),
                ('password', models.CharField(max_length=1000)),
                ('is_super_admin', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'users',
            },
        ),
    ]
