# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-26 11:00
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stalker_app', '0002_auto_20171126_1100'),
    ]

    operations = [
        migrations.AddField(
            model_name='coordinate',
            name='longitude',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=10, validators=[django.core.validators.MaxValueValidator(180, message='Longitude must be up to 180'), django.core.validators.MinLengthValidator(-90, message='Longitude must be a minimum of                 -180')]),
        ),
        migrations.AlterField(
            model_name='coordinate',
            name='latitude',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=10, validators=[django.core.validators.MaxValueValidator(90, message='Latitude must be up to 90'), django.core.validators.MinLengthValidator(-90, message='Latitude must be a minimum of                 -90')]),
        ),
    ]
